- title: Mentor
  at: UW Madison Directed Reading Program 
  url: https://sites.google.com/site/uwmadisondrp/
  location: Madison, WI
  years: Spring 2024
  description: Led a group of students in reading Stillwell's "Mathematics and its History".
- title: Organizer
  at: UW Madison Directed Reading Program 
  url: https://sites.google.com/site/uwmadisondrp/
  location: Madison, WI
  years: Fall 2019-Fall 2023
  description: "The DRP is a math mentoring program that pairs undergraduate students with graduate student mentors, for a semester-long independent study project."
- title: Graduate Mentor
  at: MXM Experimental Mathematics project
  location: Madison, WI
  years: Fall 2022, Spring 2023
  description: Directed advanced undergraduates on a computationally focused research project concerning identifiable linear compartmental models.
- title: Graduate Mentor
  at: Undergraduate Mentoring Program
  location: Madison, WI
  years: Fall 2022
  description: Met with a group of undergraduate math majors to give advice about how to navigate their undergrad degree, plan for grad school apps, and think about REUs and other opportunities.
- title: Graduate Mentor
  at: UW Madison
  location: Madison, WI
  years: 2022-2023
  description: Helped orient new PhD students into the PhD program at UW Madison.
  hide: true
- title: Math Meet Coordinator
  at: UW Madison
  url: "https://math.wisc.edu/mega-math-meet/"
  location: Madison, WI
  years: Spring 2022
  description: "Wrote problems and planned a math competition for over 200 middle schoolers around Wisconsin."
- title: Public Service Fellow
  at: WISCIENCE
  url: https://wiscience.wisc.edu/program/public-service-fellows
  location: Madison, WI
  years: Jan 2021-Jan 2022
  description: Met and discussed best ways to engage with the public and worked with a community partner on a web project to make arXiv easier to navigate.
- title: Mentor
  at:  First Generation Student Success
  url: https://firstgensuwmadison.wixsite.com/fgss
  location: Madison, WI
  years: Fall 2020-Spring 2021
  description: "FGSS links first-generation college students to first generation graduate and faculty mentors for monthly meetings. "
- title: Volunteer
  at: AMS Fall Central Sectional
  years: Sep 2019
  location: Madison, WI
  description: "Signed in attendees to the 3-day AMS Fall central sectional meeting."
  hide: true
- title: Student Ambassador
  at: College of Charleston School of Sciences and Mathematics
  years: Sep 2018-May 2019
  location: Charleston, SC
  description: Select group of 9 students who have demonstrated outstanding academic achievement and exemplar student leadership. Represent the School of Sciences and Mathematics at College of Charleston to incoming students and other interest groups.
  hide: true
- title: Student Vice President
  at: Phi Kappa Phi
  years: Apr 2017-May 2019
  location: Charleston, SC
  description: Met with board to coordinate volunteer opportunities and promote education throughout the College of Charleston campus. Helped organize events on campus for Phi Kappa Phi members. 
  hide: true
- title: Volunteer
  at: AMS Spring Southeastern Sectional Meeting
  years: Mar 2017
  location: Charleston, SC
  description: "Signed in attendees to the 3-day AMS Spring southeastern sectional meeting."
  hide: true
- title: Volunteer
  at: College of Charleston Math Meet
  years: 2016-2018
  url: https://mathmeet.cofc.edu/
  location: Charleston, SC
  description: "Volunteered to oversee various parts of the planned activities including judging timed sprints and signing students in."
  hide: true
- title: Volunteer Tutor
  at: Trident Literacy Association
  years: Oct 2015-Oct 2016
  url: https://tridentlit.org/
  location: Charleston, SC
  description: "Helped weekly to prepare nontraditional students for their GED."
- title: Cofounder & Board Member
  at: The Cancer Chase
  years: Feb 2015-Oct 2017
  url: https://cancerchase5k.racesonline.com/
  location: Fort Mill, SC
  description: "Helped direct an annual 5k run benefiting Carolinas HealthCare System's Levine Cancer Institute. Rallied support from local businesses to raise over $15,000 annually."
  